export const FIND_ALL = 'FIND_ALL';
export const FIND_RESOURCE = 'FIND_RESOURCE';
export const CREATE_RESOURCE = 'CREATE_RESOURCE';
export const UPDATE_RESOURCE = 'UPDATE_RESOURCE';
export const DELETE_RESOURCE = 'DELETE_RESOURCE';
export const MODEL_ERROR = 'MODEL_ERROR';
